# Generated by Django 4.1.4 on 2023-01-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('landmark', models.CharField(max_length=50)),
            ],
        ),
    ]
