# Generated by Django 4.1.4 on 2023-02-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_user',
            name='city',
            field=models.CharField(default='Trivandrum', max_length=50),
        ),
        migrations.AddField(
            model_name='our_user',
            name='state',
            field=models.CharField(default='state', max_length=50),
        ),
    ]
