# Generated by Django 4.1.4 on 2023-02-02 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_our_user_city_our_user_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='our_user',
            old_name='Address',
            new_name='address',
        ),
    ]
