# Generated by Django 4.1.4 on 2023-02-03 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cart_product_colour_variant_product_size_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_paid',
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
